version: "3.4"
services: 
    db:
      restart: always
      image: mysql:8.0
      container_name: mysql_container
      environment:
        TZ: UTC
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: trace_payment_dev
      ports:
        - 3306:3306
      networks:
        - trace_network
      volumes:
        - payment_data:/var/lib/mysql

    trace-payment-app:
      restart: always
      build:
        context: ./payment
        dockerfile: ./Dockerfile
      image: payment_api
      container_name: payment_api
      ports:
        - 8080:8080
      networks:
        - trace_network
      environment:
         PROFILE: dev
         DB_URL: jdbc:mysql://mysql_container:3306/trace_payment_dev
         DB_USERNAME: root
         DB_PASSWORD: root
      links:
        - db
      depends_on:
        - db  
      volumes:
        - "/etc/timezone:/etc/timezone:ro"
        - "/etc/localtime:/etc/localtime:ro"
     
networks:
  trace_network:
    driver: bridge

volumes:
  payment_data:
