spring:
  profiles:
    active: dev
  jackson:
    default-property-inclusion: non_null
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

