spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jackson:
    default-property-inclusion: non_null
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
