name: Test and build Kotlin app with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      working-directory: ./payment
      
    - name: Build-DB
      run: docker-compose build db

    - name: Create-DB
      run: docker-compose up -d db
      
    - name: Test and generate reports
      run: ./gradlew check jacocoTestCoverageVerification jacocoTestReport
      working-directory: ./payment
      
  build:
     needs: tests
     runs-on: ubuntu-latest

     steps:
     - uses: actions/checkout@v3
    
     - name: Build jar
       run: ./gradlew clean bootjar
       working-directory: ./payment
    
      
    
